### ISSUE TITLE
Failed to execute script main

### ISSUE THREAD

**Issue by Desmo5574** [shinrax2/PS3GameUpdateDownloader#10]
Hi shinrax2,

Great gui script that works for 90% of the games in my library. 
There are a handful of games however that cause the gui to crash. 
I input the TitleID, press Search, I'll see the name of the game/TitleID briefly and then gui crashes/closes. 
Below the crash and log files. Hopefully you've got some free time to look it over.

_crash log:_
Uncaught exception:
Type: <class 'xml.etree.ElementTree.ParseError'>
Value: syntax error: line 1, column 0
Traceback:
  File "main.py", line 14, in <module>
  File "main.py", line 11, in run
  File "gui.py", line 129, in mainWin
  File "PS3GUD.py", line 175, in checkForUpdates
  File "xml/etree/ElementTree.py", line 1347, in XML

_log:_
[INFO] 2021-04-19 14:25:17.524617 Loaded configuration file!
[INFO] 2021-04-19 14:25:17.534333 Loaded TitleDB "titledb.json"
[INFO] 2021-04-19 14:25:17.964726 PS3GameUpdateDownloader v009
[INFO] 2021-04-19 14:25:18.015941 Config File: ./config.json
[INFO] 2021-04-19 14:25:18.018692 Language: en
[INFO] 2021-04-19 14:25:18.021094 Current working directory: /vol1/Source/PS3GameUpdateDownloader
[INFO] 2021-04-19 14:25:18.023524 Compiled: True
[INFO] 2021-04-19 14:25:18.052404 PySimpleGUI version: 4.34.0 Released 18-Jan-2021
[INFO] 2021-04-19 14:25:18.056082 Python version: 3.9.1 (default, Jan  5 2021, 19:38:37) 
[GCC 8.3.0]
[INFO] 2021-04-19 14:25:18.059297 

[INFO] 2021-04-19 14:25:18.352892 Already on the newest release!
[INFO] 2021-04-19 14:25:30.150716 Game is: Macross 30: Ginga o Tsunagu Utagoe (30th Anniversary Edition) (NTSC-J)	 TitleID: BLJS10182

**Comment by shinrax2** [comment]
i did look into it and it seems sony did some changes to the update servers/cleaning out stuff
ill add a safeguard for the crash itself and some info about the the ps3 store shutdown

**Comment by Desmo5574** [comment]
That was fast...thanks!!
