### ISSUE TITLE
[Wiki] main.py should be main_ps3gud.py

### ISSUE THREAD

**Issue by rursache** [shinrax2/PS3GameUpdateDownloader#113]
There is a typo in the [Getting Started](https://github.com/shinrax2/PS3GameUpdateDownloader/wiki/Getting-Started#running-it) wiki page

The instruction to run the script should be `python main_ps3gud.py` instead of `python main.py` as there is no `main.py` in the project

**Comment by shinrax2** [comment]
fixed
thanks for reporting
