### ISSUE TITLE
Unhandled Exception with Lost Planet 2

### ISSUE THREAD

**Issue by ketxxx** [shinrax2/PS3GameUpdateDownloader#116]
I've been downloading updates for all of my PS3 games totally fine with this tool but for whatever reason whenever I try to download the Lost Planet 2 (BLES00710) update file PS3GUD just spits out an unhandled exception error. The update downloads fine to my PS3 so doesn't seem to be a Sony server issue, screenshot below. Workaround anyone? 
![1](https://github.com/shinrax2/PS3GameUpdateDownloader/assets/60001143/c7519095-29b8-49cf-9ac8-d15181d045af)

**Comment by shinrax2** [comment]
@ketxxx 
[this](https://a0.ww.np.dl.playstation.net/tpl/np/BLES00710/BLES00710-ver.xml) is the raw meta file for that titleid
it says the sony server doesnt know that title id
so either your ps3 downloads differently ( i dont think so) or lost planet 2 on your ps3 has a different title id

however i will add some code to handle that exception

**Comment by shinrax2** [comment]
if your ps3 has homebrew capabilities your could copy the downloaded update from there as a workaround maybe

**Comment by ketxxx** [comment]
Thanks @shinrax2, yes my PS3 is running homebrew, Evilnat 4.90, but I can also test to see if there is a download issue with a totally stock PS3 I have as well if you want.

**Comment by shinrax2** [comment]
@ketxxx if u can capture the network traffic of the stock ps3 it would be usefull to compare

**Comment by ketxxx** [comment]
I can see about getting that set up for you @shinrax2 but it might take a while due to real world stuff and I don't have any network packet\traffic software set up it's not usually the sort of thing I need to monitor.
