### ISSUE TITLE
Meta file for this TitleID is not available

### ISSUE THREAD

**Issue by commandcontrolQ** [shinrax2/PS3GameUpdateDownloader#150]
Tried to download updates for Minecraft: PS3 Edition and Terraria but when entering the Title ID, the correct game is recognized but it cannot find a meta file.

**Comment by szentigrad3** [comment]
same error here on 2 gran turismo games

**Comment by shinrax2** [comment]
@szentigrad3 @commandcontrolQ please give me the exact title ids so i can check if  there is some problem
otherwise if sony deleted stuff from their servers or a titleid has no updates, i cant do anything about that

**Comment by szentigrad3** [comment]
BCUS98114 BCUS98296

**Comment by shinrax2** [comment]
@szentigrad3 it seems sony's certificate doesn't verify at all on modern SSL anymore, please enable the "Bypass SSL" option to be able to download updates

**Comment by snowboyz0825** [comment]
> [@szentigrad3](https://github.com/szentigrad3) it seems sony's certificate doesn't verify at all on modern SSL anymore, please enable the "Bypass SSL" option to be able to download updates

Is the option there at all on linux or am I stupid?
