### ISSUE TITLE
Errors out if disk space below 5%

### ISSUE THREAD

**Issue by oxyacetylene** [shinrax2/PS3GameUpdateDownloader#21]
Had 14.6GB left on disk and it refused to download a 220MB update

```
[INFO] 2021-11-11 00:14:59.490585 Game is: The IdolM@ster: One for All	 TitleID: NPJB00611
*** tk version 8.6.9 detected.... patching ttk treeview code ***
[INFO] 2021-11-11 00:15:01.312551 Starting download of updates
[ERROR] 2021-11-11 00:15:01.398271 Free disc space is below 95%
[INFO] 2021-11-11 00:15:01.426473 Finished downloading 1 files!
```

Checked folder and it wasn't downloaded.
Changed to a disk with more than 5% free and it downloaded fine

**Comment by shinrax2** [comment]
there is a setting called "storage threshold" in the settings window
set that to 100% and you can download til your drive is full

ill add tooltips explaining that setting
