### ISSUE TITLE
TitleID invalid for JP PNS TitleIDs

### ISSUE THREAD

**Issue by hgdagon** [shinrax2/PS3GameUpdateDownloader#25]
Tried for NPJA00073 and NPJA00074. PS3GUD could not download the updates, claiming the TitleID was invalid. However both the XML and the updates themselves are are still available.

**Comment by shinrax2** [comment]
i will look into that

**Comment by shinrax2** [comment]
thanks for the report if you find more titleid misssing like this please dont hesitate to report
its fixed in 9ec57dc30c6992b083f3692c19a2ed12973524e0
