### ISSUE TITLE
Windows version updater error

### ISSUE THREAD

**Issue by piratesephiroth** [shinrax2/PS3GameUpdateDownloader#6]
It downloads the Linux version

**Comment by shinrax2** [comment]
i could not reproduce that

from which version were u updating?

**Comment by piratesephiroth** [comment]
uh, I don't have it anymore but it should have been the previous release that was labeled as "latest".
(v0.0.7 if you didn't delete any)

**Comment by shinrax2** [comment]
yeah due to an oversight i forgot to change how the selection works but i already fixed but after the v007 release
anyway thanks for reporting :)
