### ISSUE TITLE
Application not useable

### ISSUE THREAD

**Issue by RuralHunter** [shinrax2/PS3GameUpdateDownloader#8]
I downloaded the linux 64 bits release version. I could search with game id, got the updates list. But when I click the download button, the console outputs an error "[3434217] Failed to execute script main" and nothing happens.

I then downloaded the source. After installed the requirements I ran the main.py by "python3 main.py" as the guide. I input the same game id and the app just reported no meta file available(which could be found with the release version):
[INFO] 2021-02-10 12:02:20.257794 Game is: LittleBigPlanet 3 (NTSC-A)	 TitleID: BCAS20322
[ERROR] 2021-02-10 12:02:21.737484 Meta file for this TitleID is not available!

**Comment by shinrax2** [comment]
could you please upload the lastest log and crashlog?
it can be found in PS3GameUpdateDownloader/logs

**Comment by shinrax2** [comment]
i fixed the crash when downloading in 7b6f5bb456e0018ed624506e86ac71485c89bf91

however i still need to look into the differences when finding game updates

**Comment by RuralHunter** [comment]
cash log:
```
> cat Crash-2021-02-10_11-56-37.txt
Uncaught exception:
Type: <class 'FileNotFoundError'>
Value: [Errno 2] No such file or directory: './downloadedPKGs/LittleBigPlanet 3 (NTSC-A)[BCAS20322]/'
Traceback:
  File "main.py", line 14, in <module>
  File "main.py", line 11, in run
  File "gui.py", line 136, in mainWin
  File "PS3GUD.py", line 199, in downloadFiles
  File "shutil.py", line 1262, in disk_usage
```

**Comment by RuralHunter** [comment]
The log:
```
> cat log-2021-02-10_12-11-10.txt
[INFO] 2021-02-10 12:11:10.084483 Loaded configuration file!
[INFO] 2021-02-10 12:11:10.094494 Loaded TitleDB "titledb.json"
[INFO] 2021-02-10 12:11:10.680309 PS3GameUpdateDownloader v008
[INFO] 2021-02-10 12:11:10.687266 Config File: ./config.json
[INFO] 2021-02-10 12:11:10.700112 Language: en
[INFO] 2021-02-10 12:11:10.709647 Current working directory: /home/rhunter/ps3/PS3GameUpdateDownloader
[INFO] 2021-02-10 12:11:10.714531 Compiled: True
[INFO] 2021-02-10 12:11:10.722699 PySimpleGUI version: 4.33.0 Released 02-Jan-2021
[INFO] 2021-02-10 12:11:10.726369 Python version: 3.9.1 (default, Jan  5 2021, 19:38:37) 
[GCC 8.3.0]
[INFO] 2021-02-10 12:11:10.730496 

[INFO] 2021-02-10 12:11:12.722390 Already on the newest release!
[INFO] 2021-02-10 12:11:40.196400 Game is: LittleBigPlanet 3 (NTSC-A)	 TitleID: BCAS20322
```

**Comment by shinrax2** [comment]
finding updates should be fixed now

could you please verify that it works on your end?
https://github.com/shinrax2/PS3GameUpdateDownloader/archive/master.zip

**Comment by RuralHunter** [comment]
Yes, the search function in running source mode is working now.

**Comment by RuralHunter** [comment]
The downloading function works too.

**Comment by TonyAMG** [comment]
What about Windows version, it has the same error.

![image](https://user-images.githubusercontent.com/63655322/107779180-ab5f7000-6d4d-11eb-858b-616fbc537489.png)

And on Windows combination `Ctrl+V` (Paste) doesn't seem to work, but Linux's `Shift+Insert` works instead  ¯\_(ツ)_/¯

**Comment by shinrax2** [comment]
the downloading is fixed for all platforms however i need to release new binaries
