### ISSUE TITLE
crash v009 windows 10

### ISSUE THREAD

**Issue by xiva-wgt** [shinrax2/PS3GameUpdateDownloader#9]
[Crash-2021-04-18_23-40-31.txt](https://github.com/shinrax2/PS3GameUpdateDownloader/files/6332165/Crash-2021-04-18_23-40-31.txt)
[log-2021-04-18_23-40-10.txt](https://github.com/shinrax2/PS3GameUpdateDownloader/files/6332166/log-2021-04-18_23-40-10.txt)

Uncaught exception:
Type: <class 'xml.etree.ElementTree.ParseError'>
Value: syntax error: line 1, column 0
Traceback:
  File "main.py", line 14, in <module>
  File "main.py", line 11, in run
  File "gui.py", line 129, in mainWin
  File "PS3GUD.py", line 175, in checkForUpdates
  File "xml\etree\ElementTree.py", line 1347, in XML

**Comment by shinrax2** [comment]
i did look into it and it seems sony did some changes to the update servers/cleaning out stuff
ill add a safeguard for the crash itself and some info about the the ps3 store shutdown
