### ISSUE TITLE
Failed to obtain/convert traceback! error message

### ISSUE THREAD

**Issue by Smoukus** [shinrax2/PS3GameUpdateDownloader#92]
After trying to search for an update for Heavenly Sword (USA) - BCUS98132, I get the following error:
![image](https://github.com/shinrax2/PS3GameUpdateDownloader/assets/48409293/82519bdc-8676-4bb4-b8bd-d340d7c53018)

Searching for updates for other games works just fine.

**Comment by shinrax2** [comment]
@Smoukus if possible could please attach the crashlog from that run?
found in logs/ with the filename Crash-date-time.txt

**Comment by Smoukus** [comment]
> @Smoukus if possible could please attach the crashlog from that run? found in logs/ with the filename Crash-date-time.txt

Here you go.
[Crash-2023-07-22_18-51-29.txt](https://github.com/shinrax2/PS3GameUpdateDownloader/files/12136882/Crash-2023-07-22_18-51-29.txt)

**Comment by shinrax2** [comment]
fixed with 67d6f35fd519f79aa0b81507ba67fe07940f6aac
